### ISSUE TITLE
broken scope link

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#142]
From @v1k0d3n https://github.com/weaveworks/weave/issues/1779

Link is http://weave.works/guides/weave-scope/weave-scope-alone.html

Two instances shown by https://github.com/weaveworks/guides/search?utf8=%E2%9C%93&q=weave-scope-alone

**Comment by abuehrle** [comment]
thanks @bboreham I have re-indexed these files with Google index.

**Comment by bboreham** [comment]
Need to fix https://github.com/weaveworks/guides/blob/e8ab2e28ac85279dee2f4a8b17055b82ec3cb6d3/weave-scope-cloud-service/README.md#L18 and https://github.com/weaveworks/guides/blob/e8ab2e28ac85279dee2f4a8b17055b82ec3cb6d3/weave-scope/README.md#L8, no?

**Comment by abuehrle** [comment]
should be fixed now

**Comment by bboreham** [comment]
The shorter text still appears in `sidebarpath` of https://github.com/weaveworks/guides/blob/master/weave-scope/README.md, but that doesn't appear to be used in the current template.

**Comment by abuehrle** [comment]
I am not sure what you mean.  The short path is just a variable on where to place the file in the sidebar menu. 

Both titles are the same in this instance.

**Comment by bboreham** [comment]
I mean, the text that changed, "weave-scope-alone", still appears on line 8 of https://github.com/weaveworks/guides/blob/master/weave-scope/README.md.  I can see that this may be unimportant.

**Comment by abuehrle** [comment]
Yes, this is just a variable that I use in a Ruby script which strips the frontmatter from the markdown files and pulls together that sidebar menu.  The varible is benign in that it doesn’t appear anywhere but is used by the script to place the content into groups, with parents and children.  For example, if I had another file with the sidepath variable: start/weave-scope-alone/file-1 and /start/weave-scope-alone/file-2, the sidebar menu would group them as children beneath /start/weave-scope-alone. 

We could use this script for the Weave Net docs as well, and create a menu for them, but I need to wait and see what the overall plan for the website is. 

Here’s the script: 

https://github.com/weaveworks/website/blob/master/_plugins/sidebar_menu.rb https://github.com/weaveworks/website/blob/master/_plugins/sidebar_menu.rb
